//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSiMed_x2._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user_master
    {
        public string ENTITY_CODE { get; set; }
        [Display(Name ="User Id")]
        [DataType(DataType.PhoneNumber)]
        public int USER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USER_NAME { get; set; }

        [Display(Name = "Current Password")]
        [DataType(DataType.Password)]
        public string CURRENT_PASSWORD { get; set; }
        public System.DateTime PASSWORD_SET_DATE { get; set; }
        public string PASSWORD_1 { get; set; }
        public string PASSWORD_2 { get; set; }
        public string PASSWORD_3 { get; set; }
        public string PASSWORD_4 { get; set; }
        public string PASSWORD_5 { get; set; }
        public string LOGIN_STATUS { get; set; }
        public string BLOCK_STATUS { get; set; }
        public int LOGIN_FAIL_ATTEMPTS { get; set; }
        public string UPDATE_PASSWORD_FLAG { get; set; }
        public string ALLOW_ADJ_DIS_WAIVER { get; set; }
        public string STATUS { get; set; }
        public int USER_CREATE { get; set; }
        public System.DateTime DATE_CREATE { get; set; }
        public Nullable<int> USER_UPDATE { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public string SCHEDULE_FLG { get; set; }
        public string ACC_REG_FLAG { get; set; }
        public Nullable<int> NEW_USER_ID { get; set; }
        public string NEW_ENTITY_CODE { get; set; }
        public string ENTITY_GROUP { get; set; }
        public string DOCTOR_TYPE { get; set; }
    }
}
